extends SceneTree
## One-off CLI tool: writes the shooter mode's input actions into
## project.godot via ProjectSettings, so the resource syntax is always
## generated by the engine itself instead of hand-typed.
## Run: tools/godot/Godot_v4.7.1-stable_win64_console.exe --headless --path . --script tools/setup_shooter_input.gd

func _initialize() -> void:
	_add_action("shooter_move_left", [_key(65), _joy_axis(0, -1.0)])
	_add_action("shooter_move_right", [_key(68), _joy_axis(0, 1.0)])
	_add_action("shooter_move_up", [_key(87), _joy_axis(1, -1.0)])
	_add_action("shooter_move_down", [_key(83), _joy_axis(1, 1.0)])
	_add_action("shooter_jump", [_key(32), _joy_button(0)])
	_add_action("shooter_shoot", [_mouse(1), _key(4194326), _joy_axis(5, 1.0)])
	_add_action("shooter_reload", [_key(82), _joy_axis(4, 1.0)])
	_add_action("shooter_aim_left", [_key(4194319), _joy_axis(2, -1.0)])
	_add_action("shooter_aim_right", [_key(4194321), _joy_axis(2, 1.0)])
	_add_action("shooter_aim_up", [_key(4194320), _joy_axis(3, -1.0)])
	_add_action("shooter_aim_down", [_key(4194322), _joy_axis(3, 1.0)])
	_add_action("shooter_coords", [_key(67), _joy_button(12)])
	ProjectSettings.save()
	print("shooter input actions written")
	quit()

func _key(physical_keycode: int) -> InputEventKey:
	var e := InputEventKey.new()
	e.physical_keycode = physical_keycode
	e.device = -1
	return e

func _mouse(button_index: int) -> InputEventMouseButton:
	var e := InputEventMouseButton.new()
	e.button_index = button_index
	e.device = -1
	return e

func _joy_button(button_index: int) -> InputEventJoypadButton:
	var e := InputEventJoypadButton.new()
	e.button_index = button_index
	return e

func _joy_axis(axis: int, axis_value: float) -> InputEventJoypadMotion:
	var e := InputEventJoypadMotion.new()
	e.axis = axis
	e.axis_value = axis_value
	return e

func _add_action(action_name: String, events: Array) -> void:
	ProjectSettings.set_setting("input/" + action_name, {"deadzone": 0.2, "events": events})
